version: "3.8"
services:
  app:
    image: node:18-alpine
    container_name: todo-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules # node_modules はコンテナ内で管理
    ports:
      - "3000:3000"
    environment:
      - DOCKER_ENV=true
      - DATABASE_URL=postgresql://user:password@todo-db:5432/todo_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    command: >
      sh -c "npm install && npx prisma migrate deploy && npm run build && npm run start"

  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: todo-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data:
